# Numpy Assignment

In [1]:
import numpy as np


### Write a function so that the columns of the output matrix are powers of the input vector.

#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [2]:
def fun(vector,n,increasing=False):
    if not increasing:
        out_matrix=np.array([x**(n-i-1) for x in vector for i in range(n)]).reshape(vector.size,n)
    elif increasing:
        out_matrix=np.array([x**i for x in vector for i in range(n) ]).reshape(vector.size,n)
    
    return out_matrix

vector=np.array([5,2 ,3, 4])
n=3
matrix_decreasing=fun(vector,n,False)
matrix_increasing=fun(vector,n,True)



print("Increasing Matrix:")
print(matrix_increasing)
print()


print("Decreasing Matrix: ")
print(matrix_decreasing)
print('-'*50)

Increasing Matrix:
[[ 1  5 25]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]

Decreasing Matrix: 
[[25  5  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
--------------------------------------------------


##### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
#### The moving average sequence has n-k+1 elements as shown below.
#### The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10<br>
===== == == == == == == == == == ==<br>
Input 10 20 30 40 50 60 70 80 90 100<br>
y1 25 = (10+20+30+40)/4<br>
y2 35 = (20+30+40+50)/4<br>
y3 45 = (30+40+50+60)/4<br>
y4 55 = (40+50+60+70)/4<br>
y5 65 = (50+60+70+80)/4<br>
y6 75 = (60+70+80+90)/4<br>
y7 85 = (70+80+90+100)/4<br>
#### Thus, the moving average sequence has n-k+1=10-4+1=7 values.

### Question: Write a function to find moving average in an array over a window:
#### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
def movingAverage(vector,window):
    for i in range(len(vector)):
        new_vector=vector[i:i+window]
        if len(new_vector) < window:
            break
        else :
            print("y{} ={} ".format(i+1,(np.average(new_vector))))

print("Simple Test")
vector=np.array([10,20,30,40,50,60,70,80,90,100])
window=4
movingAverage(vector,window)
print("-"*50)
print()
# testing
print("Final Test")
vector=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window=3
movingAverage(vector,window)

Simple Test
y1 =25.0 
y2 =35.0 
y3 =45.0 
y4 =55.0 
y5 =65.0 
y6 =75.0 
y7 =85.0 
--------------------------------------------------

Final Test
y1 =5.0 
y2 =4.666666666666667 
y3 =5.666666666666667 
y4 =6.666666666666667 
y5 =9.666666666666666 
y6 =28.666666666666668 
y7 =49.333333333333336 
y8 =72.66666666666667 
y9 =84.0 
y10 =93.33333333333333 
y11 =116.33333333333333 
